### ISSUE TITLE
Where is ‘Remix this’?

### ISSUE THREAD

**Issue by jpmedley** [SamsungInternet/webvr-101#3]
Please provide context around this. It’s not in the README or the index.html.

**Comment by jpmedley** [comment]
Should step 1 be, “launch the project in a web server and open the page,” or something like this.

**Comment by poshaughnessy** [comment]
Sorry about that, this is a backup of a Glitch project. I'll either make this clearer and fix the instructions, or remove this from Github.

**Comment by poshaughnessy** [comment]
I've updated the description and the README in 44e394fb73d0782897ed91a02993d7ecd88e049c. HTH.

**Comment by jpmedley** [comment]
Thanks!

(Sorry for the late reply. I've been on vacation.)

Joe Medley | Technical Writer, Chrome DevRel | jmedley@google.com |
 816-678-7195
*If an API's not documented it doesn't exist.*
